name: This is a github action
run-name: this is the run name
on: [push]              #for event triggering we use 'on' keyword
jobs: 
  Echo:                 #nested job
    runs-on: ubuntu-latest
    steps:
      - name: cat temp.txt
        run: cat temp.txt
